import Vue from 'vue';
import { Tab, Tabs,Cascader,Field,Popup,Button,IndexBar, IndexAnchor,Cell} from 'vant';
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Cascader);
Vue.use(Field);
Vue.use(Popup);
Vue.use(Button);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(Cell);